# -*- coding: utf-8 -*-
"""probability.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qekpjdZlF6GprEQVYUDohGsLJolHa2RP
"""

a = [1,2,3,4,5,6,7,8,9]
b = [0.2985, 0.1765, 0.1273, 0.0944, 0.0793, 0.0637, 0.0592, 0.0517, 0.0494]

import matplotlib.pyplot as plt
plt.bar(a,b)

from collections import Counter
import matplotlib.pyplot as plt
f = open("Input_Numbers.txt","r")
red = f.read()
clist = []
for i in red:
  clist.append(i)
bcount = Counter(clist)
del bcount[' ']
del bcount['\n']
temp = 0
for i in bcount.values():
  temp = temp + i
dlist = []
elist = []
sum = 0
for k in range(1,10):
  for i,j in bcount.items():
    if(str(k) == i):
      dlist.append(i)
      sum = sum + j
      elist.append(sum/temp)
plt.bar(dlist,elist)

import matplotlib.pyplot as plt
f = open("Input_Numbers.txt","r")
red = f.read()
clist = []
for i in red:
  if (i != '\n'):
    clist.append(int(i))
plt.hist(clist, bins=[1,2,3,4,5,6,7,8,9,10])
plt.show()